/*-
 * Copyright (c)2025 YAMAMOTO Takashi,
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

/*
 * https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.180-4.pdf
 */

#include <assert.h>
#include <float.h>
#include <inttypes.h>
#include <math.h>
#include <stdint.h>
#include <stdio.h>

/*
 * return the first 32-bit of fractional part,
 * assuming IEEE 754 binary64.
 */
static uint32_t
fraction(double d)
{
        union {
                double d;
                uint64_t u;
        } u;
        u.d = d;
        const unsigned int bits = 32;
        const unsigned int bias = DBL_MAX_EXP - 1; /* emax */
        const unsigned int fracbits = DBL_MANT_DIG - 1;
        const uint64_t expmask = bias | (bias << 1);
        const uint64_t fracmask = (UINT64_C(1) << fracbits) - 1;
        uint64_t exp = (u.u >> fracbits) & expmask;
        uint64_t frac = u.u & fracmask;
        assert(exp >= bias);
        exp -= bias;
        assert(exp <= (fracbits - bits));
        return frac >> (fracbits - bits - exp);
}

int
main(int argc, char **argv)
{
        unsigned int primes[64];
        unsigned int n = 0;
        unsigned int x = 2; /* first prime */

        /* generate primes */
        do {
                unsigned int i;
                for (i = 0; i < n; i++) {
                        if ((x % primes[i]) == 0) {
                                goto next;
                        }
                }
                primes[n++] = x;
        next:
                x++;
        } while (n < 64);
        unsigned int i;
#if 0
        for (i = 0; i < 64; i++) {
                printf("%u-th prime = %u\n", i, primes[i]);
        }
#endif
        assert(primes[63] == 311);
        assert(fraction(cbrt((double)primes[63])) == 0xc67178f2);

        /* generate static C arrays for sha-256 */
        printf("/* generated by gen.c */\n");
        printf("/* https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.180-4.pdf "
               "*/\n");
        printf("/* 5.3.3 */\n");
        printf("static uint32_t H[] = {\n");
        for (i = 0; i < 8; i++) {
                double d = sqrt((double)primes[i]);
                printf("\t[%u] = 0x%" PRIx32 ",\n", i, fraction(d));
        }
        printf("};\n");
        printf("/* 4.2.2 */\n");
        printf("static uint32_t K[] = {\n");
        for (i = 0; i < 64; i++) {
                double d = cbrt((double)primes[i]);
                printf("\t[%u] = 0x%" PRIx32 ",\n", i, fraction(d));
        }
        printf("};\n");
}
