/*
 * https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.180-4.pdf
 */

#include <assert.h>
#include <inttypes.h>
#include <math.h>
#include <stdint.h>
#include <stdio.h>

/*
 * return the first 32-bit of fractional part,
 * assuming IEEE 754 binary64.
 */
static uint32_t
fraction(double d)
{
        union {
                double d;
                uint64_t u;
        } u;
        u.d = d;
        uint64_t exp = (u.u >> 52) & 0x7ff;
        uint64_t frac = u.u & ((UINT64_C(1) << 52) - 1);
        assert(exp >= 1023);
        exp -= 1023;
        assert(exp <= 20);
        return frac >> (20 - exp);
}

int
main(int argc, char **argv)
{
        unsigned int primes[64];
        unsigned int n = 0;
        unsigned int x = 2; /* first prime */

        /* generate primes */
        do {
                unsigned int i;
                for (i = 0; i < n; i++) {
                        if ((x % primes[i]) == 0) {
                                goto next;
                        }
                }
                primes[n++] = x;
        next:
                x++;
        } while (n < 64);
        unsigned int i;
#if 0
    for (i = 0; i < 64; i++) {
        printf("%u-th prime = %u\n", i, primes[i]);
    }
#endif
        assert(primes[63] == 311);

        /* generate static C arrays for sha-256 */
        printf("/* generated by gen.c */\n");
        printf("/* https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.180-4.pdf "
               "*/\n");
        printf("/* 5.3.3 */\n");
        printf("static uint32_t H[] = {\n");
        for (i = 0; i < 8; i++) {
                double d = sqrt((double)primes[i]);
                printf("\t[%u] = 0x%" PRIx32 ",\n", i, fraction(d));
        }
        printf("};\n");
        printf("/* 4.2.2 */\n");
        printf("static uint32_t K[] = {\n");
        for (i = 0; i < 64; i++) {
                double d = cbrt((double)primes[i]);
                printf("\t[%u] = 0x%" PRIx32 ",\n", i, fraction(d));
        }
        printf("};\n");
}
