# /*-
#  * Copyright (c)2025 YAMAMOTO Takashi,
#  * All rights reserved.
#  *
#  * Redistribution and use in source and binary forms, with or without
#  * modification, are permitted provided that the following conditions
#  * are met:
#  * 1. Redistributions of source code must retain the above copyright
#  *    notice, this list of conditions and the following disclaimer.
#  * 2. Redistributions in binary form must reproduce the above copyright
#  *    notice, this list of conditions and the following disclaimer in the
#  *    documentation and/or other materials provided with the distribution.
#  *
#  * THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
#  * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
#  * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
#  * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
#  * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
#  * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
#  * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
#  * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
#  * SUCH DAMAGE.
#  */

from mpmath import mp
from primePy import primes
import sys

ps = primes.first(80)


def frac(v, bits):
    x = 2**bits
    return int((v * x) % x)


def sha256_table():
    print(
        """
/* generated by gen.py */
/* https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.180-4.pdf */
/* 5.3.3 */
static uint32_t H[] = {
"""[
            1:-1
        ]
    )
    for i, x in enumerate(ps[:8]):
        v = frac(mp.sqrt(mp.mpf(x)), 32)
        print(f"[{i}] = 0x{v:08x},")
    print(
        """
};
/* 4.2.2 */
static uint32_t K[] = {
"""[
            1:-1
        ]
    )
    for i, x in enumerate(ps[:64]):
        v = frac(mp.cbrt(mp.mpf(x)), 32)
        print(f"[{i}] = 0x{v:08x},")
    print("};")


def sha512_table():
    print(
        """
/* generated by gen.py */
/* https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.180-4.pdf */
/* 5.3.5 */
static uint64_t H[] = {
"""[
            1:-1
        ]
    )
    for i, x in enumerate(ps[:8]):
        v = frac(mp.sqrt(mp.mpf(x)), 64)
        print(f"[{i}] = 0x{v:016x},")
    print(
        """
};
/* 4.2.3 */
static uint64_t K[] = {
"""[
            1:-1
        ]
    )
    for i, x in enumerate(ps[:80]):
        v = frac(mp.cbrt(mp.mpf(x)), 64)
        print(f"[{i}] = 0x{v:016x},")
    print("};")


def header():
    print(open("LICENSE").read())


mp.prec = 128
if len(sys.argv) > 1 and sys.argv[1] == "sha512":
    header()
    sha512_table()
else:
    header()
    sha256_table()
