/*-
 * Copyright (c)2025 YAMAMOTO Takashi,
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

/* generated by gen.py */
/* https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.180-4.pdf */
/* 5.3.5 */
static uint64_t H[] = {
        [0] = 0x6a09e667f3bcc908, [1] = 0xbb67ae8584caa73b,
        [2] = 0x3c6ef372fe94f82b, [3] = 0xa54ff53a5f1d36f1,
        [4] = 0x510e527fade682d1, [5] = 0x9b05688c2b3e6c1f,
        [6] = 0x1f83d9abfb41bd6b, [7] = 0x5be0cd19137e2179,
};
/* 4.2.3 */
static uint64_t K[] = {
        [0] = 0x428a2f98d728ae22,  [1] = 0x7137449123ef65cd,
        [2] = 0xb5c0fbcfec4d3b2f,  [3] = 0xe9b5dba58189dbbc,
        [4] = 0x3956c25bf348b538,  [5] = 0x59f111f1b605d019,
        [6] = 0x923f82a4af194f9b,  [7] = 0xab1c5ed5da6d8118,
        [8] = 0xd807aa98a3030242,  [9] = 0x12835b0145706fbe,
        [10] = 0x243185be4ee4b28c, [11] = 0x550c7dc3d5ffb4e2,
        [12] = 0x72be5d74f27b896f, [13] = 0x80deb1fe3b1696b1,
        [14] = 0x9bdc06a725c71235, [15] = 0xc19bf174cf692694,
        [16] = 0xe49b69c19ef14ad2, [17] = 0xefbe4786384f25e3,
        [18] = 0x0fc19dc68b8cd5b5, [19] = 0x240ca1cc77ac9c65,
        [20] = 0x2de92c6f592b0275, [21] = 0x4a7484aa6ea6e483,
        [22] = 0x5cb0a9dcbd41fbd4, [23] = 0x76f988da831153b5,
        [24] = 0x983e5152ee66dfab, [25] = 0xa831c66d2db43210,
        [26] = 0xb00327c898fb213f, [27] = 0xbf597fc7beef0ee4,
        [28] = 0xc6e00bf33da88fc2, [29] = 0xd5a79147930aa725,
        [30] = 0x06ca6351e003826f, [31] = 0x142929670a0e6e70,
        [32] = 0x27b70a8546d22ffc, [33] = 0x2e1b21385c26c926,
        [34] = 0x4d2c6dfc5ac42aed, [35] = 0x53380d139d95b3df,
        [36] = 0x650a73548baf63de, [37] = 0x766a0abb3c77b2a8,
        [38] = 0x81c2c92e47edaee6, [39] = 0x92722c851482353b,
        [40] = 0xa2bfe8a14cf10364, [41] = 0xa81a664bbc423001,
        [42] = 0xc24b8b70d0f89791, [43] = 0xc76c51a30654be30,
        [44] = 0xd192e819d6ef5218, [45] = 0xd69906245565a910,
        [46] = 0xf40e35855771202a, [47] = 0x106aa07032bbd1b8,
        [48] = 0x19a4c116b8d2d0c8, [49] = 0x1e376c085141ab53,
        [50] = 0x2748774cdf8eeb99, [51] = 0x34b0bcb5e19b48a8,
        [52] = 0x391c0cb3c5c95a63, [53] = 0x4ed8aa4ae3418acb,
        [54] = 0x5b9cca4f7763e373, [55] = 0x682e6ff3d6b2b8a3,
        [56] = 0x748f82ee5defb2fc, [57] = 0x78a5636f43172f60,
        [58] = 0x84c87814a1f0ab72, [59] = 0x8cc702081a6439ec,
        [60] = 0x90befffa23631e28, [61] = 0xa4506cebde82bde9,
        [62] = 0xbef9a3f7b2c67915, [63] = 0xc67178f2e372532b,
        [64] = 0xca273eceea26619c, [65] = 0xd186b8c721c0c207,
        [66] = 0xeada7dd6cde0eb1e, [67] = 0xf57d4f7fee6ed178,
        [68] = 0x06f067aa72176fba, [69] = 0x0a637dc5a2c898a6,
        [70] = 0x113f9804bef90dae, [71] = 0x1b710b35131c471b,
        [72] = 0x28db77f523047d84, [73] = 0x32caab7b40c72493,
        [74] = 0x3c9ebe0a15c9bebc, [75] = 0x431d67c49c100d4c,
        [76] = 0x4cc5d4becb3e42b6, [77] = 0x597f299cfc657e2a,
        [78] = 0x5fcb6fab3ad6faec, [79] = 0x6c44198c4a475817,
};
